#!/usr/bin/env bash
# Based on https://github.com/dwmkerr/java-maven-standard-version-sample/blob/master/.githooks/commit-msg

# Create a regex for a conventional commit.
conventional_commit_regex="^(update|feat|improv|perf|fix|refactor|style|docs|ci|build|test|chore|revert)(\([a-z \-]+\))?!?: .+$"

# Get the commit message (the parameter we're given is just the path to the temporary file which holds the message).
commit_message=$(cat "$1")

# Check the message, if we match, all good baby.
if [[ "$commit_message" =~ $conventional_commit_regex ]]; then
   echo -e "\e[32mCommit message meets Conventional Commit standards...\e[0m"
   exit 0
fi

# Uh-oh, this is not a conventional commit, show an example and link to the spec.
echo -e "\e[31mThe commit message does not meet the Conventional Commit standard\e[0m"
echo "Examples of valid messages can be found at: https://github.com/Gilded-Games/The-Aether/blob/1.19/docs/references/COMMITS.md#examples"
echo "More details at: https://www.conventionalcommits.org/en/v1.0.0-beta.4/"
exit 1
