org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

# Mod
mod_id=aether
mod_group=com.aetherteam.aether
mod_name=The Aether
mod_version=1.5.11
mod_license=Assets: All Rights Reserved; Code: LGPL-3.0
mod_url=https://modrinth.com/mod/aether
mod_update=https://github.com/The-Aether-Team/The-Aether/raw/1.21.1-develop-fabric/update.json
mod_tracker=https://github.com/The-Aether-Team/The-Aether/issues
mod_credits=The Aether Team, former Aether Team Collaborators for their prior work on The Aether Mod, Modding Legacy for their work on Aether Legacy, GitHub contributors for their additional help, and the Wisp Forest Team for Accessories, the source code of which can be found at https://github.com/wisp-forest
mod_authors=AlphaMode, baguchi, bconlon, Blodhgarm, Burning Cactus, Drullkus, Hugo Payn, Jaryt, Katie 'Oz' Payn, quek, Raptor, reetam, RENREN, sunsette
mod_description=The Aether Team presents the original Aether mod! Up to date for modern Minecraft versions and fully compatible with multiplayer. The Aether is a dimension of floating islands high in the sky. Ascend through a Glowstone portal and begin a new survival adventure packed with new ores, mythical creatures and perilous Dungeons!

minecraft_version=1.21.1
minecraft_version_range=~1.21

fabric_version=0.103.0+1.21.1
fabric_version_range=*

fabric_loader_version=0.16.5
fabric_loader_version_range=>=0.16.2

mixin_extra_version=0.5.0-beta.3

# Dependencies
nitrogen_version=1.21.1-1.1.22-beta.2-fabric
cumulus_version=1.21.1-2.0.8-fabric
accessories_version=1.1.0-beta.48
debugutils_version=1.0.6
jei_version=19.21.0.246
jade_version=16.0.4+fabric
lootr_version=1.10.33.85
rei_version=16.0.783
cloth_config_version=15.0.140
architectury_version=13.0.6

forge_config_version=21.1.1
forge_config_screen_version=8.0.2

modmenu_version=11.0.3

# Publishing
curseforge_id=255308
modrinth_id=YhmgMVyu
version_type=release

# Follow the README's guide to figure out how to import these.
port_lib_modules = base,config,item_abilities,loot,lazy_registration,recipe_book_categories
# Porting Lib's jar in jar is broken right now, so we need to import module dependencies separately.
port_lib_temp_modules = accessors,common,conditions,core,entity,extensions,gui_utils,level_events,tags,transfer
