name: '🐛 Bug Report'
description: Create an issue about a bug.
labels: [ "type/bug" ]
title: 'Bug: <title>'
body:
  - type: dropdown
    id: feat-type
    attributes:
      label: What Feature Types Apply to This Bug?
      multiple: true
      options:
        - Art
        - Audio
        - Block
        - Config
        - Copy
        - Docs
        - Entity
        - Gui
        - Item
        - System
        - World-Gen
        - Other (Please Describe)
  - type: input
    id: other-type
    attributes:
      label: Other Type
      description: If you selected other in the dropdown above, please what type it is.
    validations:
      required: false
  - type: dropdown
    id: bug-type
    attributes:
      label: What Type of Bug Is This?
      options:
        - Annoyance
        - Compatibility
        - Crash
        - Design
        - Performance
        - Unexpected Behavior
  - type: input
    id: forge-ver
    attributes:
      label: Forge Version
      description: What version of Forge are you running? This can be found on the installation jar you have downloaded, in the Mod Options menu, or the profile's version. Please note "latest" is NOT a version.
      placeholder: "39.0.0"
    validations:
      required: true
  - type: input
    id: aether-ver
    attributes:
      label: The Aether Version
      description: What version of The Aether are you running? This can be found on the jar file you have downloaded or the Mod Options menu. Please note "latest" is NOT a version. Make sure you are using The Aether I, not The Aether II. Bugs in The Aether II should be reported on it's issue tracker instead.
      placeholder: "1.1.1"
    validations:
      required: true
  - type: input
    id: mod-conflict
    attributes:
      label: Is This Bug a Conflict With Another Mod?
      description: If this happens due to another mod, please put the name and version of the mod here. Leave blank otherwise.
    validations:
      required: false
  - type: input
    id: client-log
    attributes:
      label: Client Log
      description: A **[Gist](https://gist.github.com/)** link to the full game log. This can be found in the game files under the `logs` folder. Though not necessary, a client log can help diagnose an issue better in case a bug is caused by a reported error. Provide the `latest.log` or `debug.log` file as a Gist as soon as you find the bug, as these files are reset every time the game is opened.
  - type: input
    id: crash-log
    attributes:
      label: Crash Report (if applicable)
      description: A **[Gist](https://gist.github.com/)** link to the crash report. This can be found in the game files under the `crash-reports` folder, and all the contents of the file should be pasted into the Gist file. If the bug does not result in a crash, ignore this field.
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: A detailed list of how you encountered this bug if it is not immediately obvious. If the bug is immediately obvious, briefly mention how to replicate it.
      placeholder: |
        How often this happens
        1. Step 1
        2. Step 2
        3. Step 3, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What You Expect To Happen
      description: Describe what you thought was supposed to have happened. Don't worry if you think what you expected may be wrong.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What Actually Happened
      description: Describe what happened to you that wasn't to expectations.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details
      description: Provide any other information you think might be useful for this report. This may include screenshots, video footage, other mod details, anything you think might be relevant.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Please Read and Confirm The Following
      options:
        - label: I have confirmed this bug can be replicated without the use of Optifine.
          required: true
        - label: I have confirmed this bug is on the most recently supported version of Minecraft.
          required: true
        - label: I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
          required: true
        - label: I have confirmed this bug is unique and has not been reported already.
          required: true
        - label: If playing on a modpack, I have reported this bug to their issue tracker already.
          required: true
        - label: I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.
          required: true
