package com.gildedgames.aether.entity.projectile.crystal;

import com.gildedgames.aether.client.particle.AetherParticleTypes;
import com.gildedgames.aether.entity.AetherEntityTypes;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.level.Level;

/**
 * Projectile occasionally generated by the sun spirit. It can be hit back at the sun spirit to deal damage.
 */
public class IceCrystal extends AbstractCrystal {

    /**
     * Used for registering the entity. Use the other constructor to provide more context.
     */
    public IceCrystal(EntityType<? extends IceCrystal> entityType, Level level) {
        super(entityType, level);
    }

    /**
     * @param shooter - The entity that created this projectile
     */
    public IceCrystal(Level level, Entity shooter) {
        this(AetherEntityTypes.ICE_CRYSTAL.get(), level);
        this.setOwner(shooter);
        this.setPos(shooter.getX(), shooter.getY(), shooter.getZ());
        this.setDeltaMovement((0.2 + this.random.nextFloat() * 0.15 * (this.random.nextInt(2) == 0 ? 1 : -1)) / 3,
                0,
                (0.2 + this.random.nextFloat() * 0.15 * (this.random.nextInt(2) == 0 ? 1 : -1)) / 3);
    }

    @Override
    public void spawnExplosionParticles() {
        if (this.level instanceof ServerLevel level) {
            for (int i = 0; i < 20; i++) {
                double d0 = (this.random.nextFloat() - 0.5F) * 0.5;
                double d1 = (this.random.nextFloat() - 0.5F) * 0.5;
                double d2 = (this.random.nextFloat() - 0.5F) * 0.5;
                level.sendParticles(AetherParticleTypes.FROZEN.get(), this.getX(), this.getY(), this.getZ(), 1, d0 * 0.5, d1 * 0.5, d2 * 0.5, 0.0F);
            }
        }
    }

    /**
     * This is needed to make the crystal vulnerable to player attacks.
     */
    @Override
    public boolean isPickable() {
        return true;
    }
}
