name: Add pull requests to project

on:
  pull_request:
    types:
      - opened
permissions: write-all
jobs:
  add-pull-request-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/Gilded-Games/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
