name: Add pull requests to project

on:
  pull_request:
    types:
      - opened
jobs:
  add-pull-request-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/Gilded-Games/projects/2
          github-token: ${{ secrets.PROJECT_ADD_TOKEN }}
